version: '3.8'

services:
  whatsapp-webhook:
    build: .
    container_name: whatsapp-webhook
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VERIFY_TOKEN=primelegal_whatsapp_2025
      - ACCESS_TOKEN=EAAS0Lu4TybsBPVeYFoODDXRMtXZAEDGPX6s0Gxeecbrv2XCy65xBaAV2zpBfGxRepPhr7CfNpHuV5ZA1rJMv0Gx0FTH1URuTvFFRMGGckNW0PzNlOYDZACJKKfTgPzUq9avJl4onj3JWZAn7N7DhFIOAsuaUUGvdUzPjXwhT4IRFiBue0h8GH7PJIpHfsTMeEwZDZD
    networks:
      - whatsapp-network

  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    restart: unless-stopped
    ports:
      - "3002:80"
      - "3443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - whatsapp-webhook
    networks:
      - whatsapp-network

  certbot:
    image: certbot/certbot
    container_name: whatsapp-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./ssl:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email --staging -d whatsapp.webhook.primelegal.kz

volumes:
  certbot-etc:
  certbot-var:

networks:
  whatsapp-network:
    driver: bridge